# 数组类型

In [1]:
from numpy import *

## 复数数组

In [2]:
a = array([1 + 1j, 2, 3, 4])
a

array([ 1.+1.j,  2.+0.j,  3.+0.j,  4.+0.j])

In [3]:
a.dtype

dtype('complex128')

In [5]:
#实部
a.real

array([ 1.,  2.,  3.,  4.])

In [6]:
#虚部
a.imag

array([ 1.,  0.,  0.,  0.])

改变它们的值

In [7]:
a.imag = [1, 3, 5, 6]
a

array([ 1.+1.j,  2.+3.j,  3.+5.j,  4.+6.j])

In [8]:
# 复共轭
a.conj()

array([ 1.-1.j,  2.-3.j,  3.-5.j,  4.-6.j])

## 指定数组类型

构建数组的时候，数组会根据传入的内容自动判断类型：

In [2]:
a = array([0, 1.0, 2, 3])

In [3]:
a.dtype

dtype('float64')

In [4]:
a = array([0, 1.0, 2, 3], dtype=float32)

In [5]:
a.dtype

dtype('float32')

In [6]:
#无符号整数
a = array([0, 1, 2, 3], dtype=uint)

In [7]:
a = array([1, 2, 3, 4], dtype=uint)
a.tofile('foo.dat')

In [13]:
b = frombuffer(b'foo', dtype=uint8)
b

array([102, 111, 111], dtype=uint8)

In [14]:
import os
os.remove('foo.dat')


0-255 的数字可以表示ASCⅡ码，我们可以用 ord 函数来查看字符的ASCⅡ码值：

In [16]:
ord('f')

102

In [18]:
ord('9')

57

## Numpy类型

具体如下：

|  基本类型  | 可用的Numpy类型  |  备注 |
| ------------ | -----------| ------------ |
| 布尔型  |  bool |  占1个字节 |
|整型|int8，int16，int32，int64，int128，int|int和C语言中的long一样大|
|无符号整数|uint8，uint16，uint32， uint64，uint128，uint|uint和C语言中的unsigned long一样大|
|浮点数|float16, float32, float64, float, longfloat|默认为双精度 float64 ，longfloat 精度大小与系统有关|
|复数|complex64, complex128, complex, longcomplex|默认为 complex128 ，即实部虚部都为双精度|
|字符串|string, unicode|可以使用 dtype=S4 表示一个4字节字符串的数组|
|对象|object|数组中可以使用任意值|
|records|void||
|时间|datetime64， timedelta64||

任意类型的数组：

In [20]:
a = array([1, 2.2, 'hello', [10, 20, 33]], dtype=object)
a

array([1, 2.2, 'hello', [10, 20, 33]], dtype=object)

In [22]:
a * 2

array([2, 4.4, 'hellohello', [10, 20, 33, 10, 20, 33]], dtype=object)

## 类型转换

In [23]:
a = array([1.2, 3.9, 2.0], dtype=int)
a

array([1, 3, 2])

## asarray函数

array和asarray都可以将结构数据转化为ndarray，但是主要区别就是当数据源是ndarray时，array仍然会copy出一个副本，占用新的内存，但asarray不会。

In [24]:
l = [1, 2, 3]
a1 = array(l)
a2 = asarray(l)

In [25]:
print(a1)
print(a2)

[1 2 3]
[1 2 3]


In [31]:
a3 = array(a1)
a4 = asarray(a1)

In [32]:
a3 is a1

False

In [33]:
a4 is a1

True

但当类型相同的时候，asarray 并不会产生新的对象，而是使用同一个引用.

这么做的好处在与，asarray 不仅可以作用于数组，还可以将其他类型转化为数组。

有些时候为了保证我们的输入值是数组，我们需要将其使用 asarray 转化，当它已经是数组的时候，并不会产生新的对象，这样保证了效率。

## astype方法

**astype**用来做类型转换

In [34]:
a

array([1, 3, 2])

In [35]:
a.astype(float64)

array([ 1.,  3.,  2.])

astype也**不会**改变原来数组的值：

In [36]:
a

array([1, 3, 2])

另外，astype 总是返回原来数组的一份复制，即使转换的类型是相同的：

In [37]:
b = a.astype(float32)
print(a)
print(b)

[1 3 2]
[ 1.  3.  2.]


In [38]:
a is b

False

## view方法

    view([dtype, type]) 
    
生成一个相同数据，但是类型为指定新类型的矩阵。

In [39]:
a = array((1,2,3,4), dtype=int32)
a

array([1, 2, 3, 4])

view 会将 a 在内存中的表示看成是 uint8 进行解析

In [40]:
b = a.view(uint8)
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0], dtype=uint8)

修改 a 会修改 b 的值，因为共用一块内存：

In [44]:
a[0] = 128
a

array([128,   2,   3,   4])

In [45]:
b

array([128,   0,   0,   0,   2,   0,   0,   0,   3,   0,   0,   0,   4,
         0,   0,   0], dtype=uint8)

In [46]:
a[0] = 1024
b

array([0, 4, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0], dtype=uint8)