# 数组方法

In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


## 求和

In [3]:
a = array([[1,2,3], [5,6,7]])
a

array([[1, 2, 3],
       [5, 6, 7]])

求所有元素的和：

In [4]:
sum(a)

24

指定求和的维度：

In [5]:
#沿着第一维求和：
sum(a, axis=0)

array([ 6,  8, 10])

In [6]:
#沿着第二维求和：
sum(a, axis=1)

array([ 6, 18])

In [7]:
#沿着最后一维求和：
sum(a, axis=-1)

array([ 6, 18])

或者使用 sum 方法：

In [8]:
a.sum()

24

In [9]:
a.sum(axis=0)

array([ 6,  8, 10])

In [10]:
a.sum(axis=1)

array([ 6, 18])

## 求积 

In [11]:
a.prod()

1260

In [12]:
prod(a)

1260

In [13]:
prod(a, axis=0)

array([ 5, 12, 21])

## 求最大值最小值

In [16]:
a = rand(3, 4)
%precision 3
a

array([[ 0.021,  0.159,  0.368,  0.845],
       [ 0.351,  0.564,  0.968,  0.873],
       [ 0.576,  0.599,  0.558,  0.334]])

In [17]:
#全局最小
a.min()

0.021

In [18]:
# 沿着某个轴的最小：
a.min(axis=0)

array([ 0.021,  0.159,  0.368,  0.334])

In [19]:
a.max()

0.968

In [21]:
a.max(axis=1)

array([ 0.845,  0.968,  0.599])

## 最大最小值的位置

使用 argmin, argmax 方法：

In [22]:
a.argmin()

0

In [23]:
a.argmax()

6

## 均值

可以使用 **mean** 方法：

In [24]:
a.mean()

0.518

In [25]:
a.mean(axis=0)

array([ 0.316,  0.441,  0.631,  0.684])

In [26]:
mean(a, axis=1)

array([ 0.348,  0.689,  0.517])

还可以使用 **average** 函数：

In [27]:
average(a, axis=1)

array([ 0.348,  0.689,  0.517])

average 函数还支持加权平均：

In [29]:
average(a, axis=1, weights=[1,2,3,4])

array([ 0.482,  0.787,  0.478])

## 标准差

In [30]:
# 标准差
a.std(axis=1)

array([ 0.312,  0.246,  0.107])

In [31]:
# 方差
a.var(axis=1)

array([ 0.097,  0.06 ,  0.011])

In [32]:
std(a, axis=1)

array([ 0.312,  0.246,  0.107])

In [33]:
var(a, axis=1)

array([ 0.097,  0.06 ,  0.011])

## clip方法 

    numpy.clip(a, a_min, a_max, out=None)

clip这个函数将数组中的元素限制在a_min, a_max之间，大于a_max的就使得它等于 a_max，小于a_min,的就使得它等于a_min。

In [35]:
a

array([[ 0.021,  0.159,  0.368,  0.845],
       [ 0.351,  0.564,  0.968,  0.873],
       [ 0.576,  0.599,  0.558,  0.334]])

In [36]:
a.clip(0.2, 0.5)

array([[ 0.2  ,  0.2  ,  0.368,  0.5  ],
       [ 0.351,  0.5  ,  0.5  ,  0.5  ],
       [ 0.5  ,  0.5  ,  0.5  ,  0.334]])

## ptp 方法

计算最大值和最小值的差

In [37]:
a.ptp(axis=1)

array([ 0.824,  0.617,  0.265])

In [39]:
ptp(a)

0.946

## round 方法

近似，默认到整数：

In [54]:
a = array([1.35, 2.5, 1.5, 3.5, 4.5, 1.6])

In [55]:
a.round()

array([ 1.,  2.,  2.,  4.,  4.,  2.])

近似到一位小数：

In [56]:
a.round(decimals=1)

array([ 1.4,  2.5,  1.5,  3.5,  4.5,  1.6])