# 数组排序

In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


## sort函数

sort 返回的结果是从小到大排列的。

In [2]:
names = array(['bob', 'tom', 'jerry', 'ad'])
weights = array([9.9, 19.9, 2, 66])

sort(weights)

array([  2. ,   9.9,  19.9,  66. ])

In [3]:
sort(names)

array(['ad', 'bob', 'jerry', 'tom'], 
      dtype='<U5')

## argsort函数


argsort 返回从小到大的排列在数组中的索引位置：

In [4]:
index = argsort(weights)
index

array([2, 0, 1, 3], dtype=int64)

可以用它来进行索引：

In [5]:
weights[index]

array([  2. ,   9.9,  19.9,  66. ])

使用函数并不会影响原数组的值

In [6]:
weights

array([  9.9,  19.9,   2. ,  66. ])

## sort 和 argsort 方法

数组也支持方法操作：

In [7]:
weights.argsort()

array([2, 0, 1, 3], dtype=int64)

argsort 方法与 argsort 函数的使用没什么区别，也不会改变数组的值。

In [8]:
weights

array([  9.9,  19.9,   2. ,  66. ])

但是 sort方法会改变数组的值：

In [9]:
weights.sort()
weights

array([  2. ,   9.9,  19.9,  66. ])

## 二维数组排序

对于多维数组，sort方法默认沿着最后一维开始排序：

In [10]:
a = array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .7]
    ])
a

array([[ 0.2,  0.1,  0.5],
       [ 0.4,  0.8,  0.3],
       [ 0.9,  0.6,  0.7]])

对于二维数组，默认相当于对每一行进行排序：

In [11]:
sort(a)

array([[ 0.1,  0.2,  0.5],
       [ 0.3,  0.4,  0.8],
       [ 0.6,  0.7,  0.9]])

In [12]:
sort(a, axis=0)

array([[ 0.2,  0.1,  0.3],
       [ 0.4,  0.6,  0.5],
       [ 0.9,  0.8,  0.7]])

## searchsorted 函数

    searchsorted(sorted_array, values)
    #Find indices where elements should be inserted to maintain order
    
searchsorted 接受两个参数，其中，第一个必需是已排序的数组。

In [18]:
sorted_array = array([1, 2, 3, 4, 5])
values = array([6,0])

In [19]:
searchsorted(sorted_array, values)

array([5, 0], dtype=int64)

利用插入位置，可以将数组中所有在两个值之间的值提取出来：

In [22]:
data = rand(100)
data.sort()

In [23]:
bounds = 0.4, 0.6
low_idx, high_idx = searchsorted(data, bounds)

In [24]:
data[low_idx:high_idx]

array([ 0.40084216,  0.41304533,  0.41588928,  0.42693269,  0.4333748 ,
        0.43722579,  0.44192625,  0.44646372,  0.46357324,  0.49547749,
        0.5022423 ,  0.52421799,  0.55759801,  0.56275552,  0.58961157,
        0.59052663,  0.59830727])

In [37]:
a = 0.4 < data 
b = data < 0.6
a & b

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [39]:
data[a & b]

array([ 0.40084216,  0.41304533,  0.41588928,  0.42693269,  0.4333748 ,
        0.43722579,  0.44192625,  0.44646372,  0.46357324,  0.49547749,
        0.5022423 ,  0.52421799,  0.55759801,  0.56275552,  0.58961157,
        0.59052663,  0.59830727])

In [40]:
data[0.4 < data < 0.6]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()