# 数组形状

In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


## 修改数组的形状

In [2]:
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
#将形状修改为2*3
a.shape = 2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

与之对应的方法是 reshape ，但它不会修改原来数组的值，而是返回一个新的数组：

In [4]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
a

array([[0, 1, 2],
       [3, 4, 5]])

shape 和 reshape 方法不能改变数组中元素的总数，否则会报错：

In [6]:
a.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

## 使用 newaxis 增加数组维数

In [9]:
a = arange(3)
a

array([0, 1, 2])

In [10]:
shape(a)

(3,)

In [11]:
y = a[newaxis, :]
y

array([[0, 1, 2]])

In [12]:
y = a[:, newaxis]
y

array([[0],
       [1],
       [2]])

In [15]:
y = a[newaxis, newaxis, :]
print(y)
print(y.shape)

[[[0 1 2]]]
(1, 1, 3)


## squeeze 方法去除多余的轴

squeeze 返回一个将所有长度为1的维度去除的新数组。

In [16]:
a = arange(6)
a.shape = 2, 1, 3
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [17]:
b = a.squeeze()
print(a)
print(b)

[[[0 1 2]]

 [[3 4 5]]]
[[0 1 2]
 [3 4 5]]


## 数组转置

使用 transpose 返回数组的转置，本质上是将所有维度反过来：

In [18]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [19]:
a.transpose()

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [20]:
#或者使用缩写属性：
a.T

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [22]:
a.T.shape

(3, 1, 2)

转置只是交换了轴的位置。

另一方面，转置返回的是对原数组的另一种view，所以改变转置会改变原来数组的值。

In [27]:
b = a.T
b[0,0] = [9, 10]
print(b)
a

[[[ 9 10]]

 [[ 1  4]]

 [[ 2  5]]]


array([[[ 9,  1,  2]],

       [[10,  4,  5]]])

## 数组连接

有时我们需要将不同的数组按照一定的顺序连接起来：

    concatenate((a0,a1,...,aN), axis=0)
    
注意，这些数组要用 () 包括到一个元组中去。

除了给定的轴外，这些数组其他轴的长度必须是一样的。

In [28]:
x = array([
        [0,1,2],
        [10,11,12]
    ])
y = array([
        [50,51,52],
        [60,61,62]
    ])
print(x.shape)
print(y.shape)

(2, 3)
(2, 3)


In [31]:
z = concatenate((x, y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [32]:
z.shape

(4, 3)

In [33]:
# 沿着第二维
z = concatenate((x, y), axis=1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

注意到这里 x 和 y 的形状是一样的，还可以将它们连接成三维的数组，但是 concatenate 不能提供这样的功能，不过可以这样：

In [34]:
z = array((x, y))
z

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[50, 51, 52],
        [60, 61, 62]]])

事实上，Numpy提供了分别对应这三种情况的函数：

* vstack
* hstack
* dstack

In [35]:
vstack((x,y))

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [37]:
hstack((x,y))

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [38]:
dstack((x,y))

array([[[ 0, 50],
        [ 1, 51],
        [ 2, 52]],

       [[10, 60],
        [11, 61],
        [12, 62]]])

In [39]:
concatenate((x, y), axis=2)

IndexError: axis 2 out of bounds [0, 2)

## Flatten 数组

flatten 方法的作用是将多维数组转化为1维数组：

In [41]:
a = array([[1, 2],
           [3, 4]])
b = a.flatten()
b

array([1, 2, 3, 4])

返回的是数组的复制，因此，改变 b 并不会影响 a 的值：

In [42]:
b[0] = 10
print(b)
print(a)

[10  2  3  4]
[[1 2]
 [3 4]]


## flat 属性

还可以使用数组自带的 flat 属性， a.flat 相当于返回了所有元组组成的一个迭代器：

In [43]:
a.flat

In [45]:
b = a.flat
b[0]

1

但此时修改 b 的值会影响 a ：

In [47]:
b[0] = 10
a

array([[10,  2],
       [ 3,  4]])

In [48]:
a.flat[:]

array([10,  2,  3,  4])

## ravel方法

除此之外，还可以使用 ravel 方法，ravel 使用高效的表示方式：

In [49]:
a = array([[0,1],
           [2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])

修改 b 会改变 a ：

In [50]:
b[0] = 10
a

array([[10,  1],
       [ 2,  3]])

但另一种情况下：

In [51]:
a = array([[0,1],
           [2,3]])
aa = a.transpose()
b = aa.ravel()
b

array([0, 2, 1, 3])

In [52]:
aa

array([[0, 2],
       [1, 3]])

In [53]:
b[0] = 10

In [54]:
aa

array([[0, 2],
       [1, 3]])

In [55]:
a

array([[0, 1],
       [2, 3]])

可以看到，在这种情况下，修改 b 并不会改变 aa 的值，原因是我们用来 ravel 的对象 aa 本身是 a 的一个view。

## atleast_xd 函数

保证数组至少有x维

In [58]:
a = 1
atleast_2d(a)

array([[1]])

In [62]:
b = atleast_3d(a)
b.shape

(1, 1, 1)

In [63]:
c = atleast_4d(a)
b.shape

NameError: name 'atleast_4d' is not defined

x 可以取值 1，2，3。

在Scipy库中，这些函数被用来保证输入满足一定的条件：

|用法|Scipy中出现的次数|
|:--|:--|
|value.flaten() <br> value.flat <br> value.ravel()| 2000次|
|atleast_1d(value) <br> atleast_2d(value)|700次|
|asarray(value)|4000次|