# 对角线

In [1]:
import numpy as np

In [18]:
a = np.array([11,21,31,12,22,32,13,23,33])
a.shape = 3, 3
a

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [19]:
# 查看对角线元素
a.diagonal()

array([11, 22, 33])

可以使用偏移来查看它的次对角线，正数表示右移，负数表示左移：

In [20]:
a.diagonal(offset = 1)

array([21, 32])

In [21]:
a.diagonal(offset = -1)

array([12, 23])

可以使用花式索引来得到对角线：

In [22]:
i = [0, 1, 2]
a[i, i]

array([11, 22, 33])

In [23]:
# 更新对角线的值：
a[i, i] = 1
a

array([[ 1, 21, 31],
       [12,  1, 32],
       [13, 23,  1]])

In [24]:
# 修改次对角线的值：
i = np.array([0, 1])
a[i, i + 1] = 2
a

array([[ 1,  2, 31],
       [12,  1,  2],
       [13, 23,  1]])

In [25]:
a[i + 1, i] = 3
a

array([[ 1,  2, 31],
       [ 3,  1,  2],
       [13,  3,  1]])