# 数组属性方法总结

<table align="center">
<thead><tr>
<th></th>
<th>作用</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td><strong>基本属性</strong></td>
</tr>
<tr>
<td><code>a.dtype</code></td>
<td>数组元素类型 <code>float32,uint8,...</code></td>
</tr>
<tr>
<td><code>a.shape</code></td>
<td>数组形状 <code>(m,n,o,...)</code></td>
</tr>
<tr>
<td><code>a.size</code></td>
<td>数组元素数</td>
</tr>
<tr>
<td><code>a.itemsize</code></td>
<td>每个元素占字节数</td>
</tr>
<tr>
<td><code>a.nbytes</code></td>
<td>所有元素占的字节</td>
</tr>
<tr>
<td><code>a.ndim</code></td>
<td>数组维度</td>
</tr>
<tr>
<td>2</td>
<td><strong>形状相关</strong></td>
</tr>
<tr>
<td><code>a.flat</code></td>
<td>所有元素的迭代器</td>
</tr>
<tr>
<td><code>a.flatten()</code></td>
<td>返回一个1维数组的复制</td>
</tr>
<tr>
<td><code>a.ravel()</code></td>
<td>返回一个1维数组，高效</td>
</tr>
<tr>
<td><code>a.resize(new_size)</code></td>
<td>改变形状</td>
</tr>
<tr>
<td><code>a.swapaxes(axis1, axis2)</code></td>
<td>交换两个维度的位置</td>
</tr>
<tr>
<td><code>a.transpose(*axex)</code></td>
<td>交换所有维度的位置</td>
</tr>
<tr>
<td><code>a.T</code></td>
<td>转置，<code>a.transpose()</code></td>
</tr>
<tr>
<td><code>a.squeeze()</code></td>
<td>去除所有长度为1的维度</td>
</tr>
<tr>
<td>3</td>
<td><strong>填充复制</strong></td>
</tr>
<tr>
<td><code>a.copy()</code></td>
<td>返回数组的一个复制</td>
</tr>
<tr>
<td><code>a.fill(value)</code></td>
<td>将数组的元组设置为特定值</td>
</tr>
<tr>
<td>4</td>
<td><strong>转化</strong></td>
</tr>
<tr>
<td><code>a.tolist()</code></td>
<td>将数组转化为列表</td>
</tr>
<tr>
<td><code>a.tostring()</code></td>
<td>转换为字符串</td>
</tr>
<tr>
<td><code>a.astype(dtype)</code></td>
<td>转化为指定类型</td>
</tr>
<tr>
<td><code>a.byteswap(False)</code></td>
<td>转换大小字节序</td>
</tr>
<tr>
<td><code>a.view(type_or_dtype)</code></td>
<td>生成一个使用相同内存，但使用不同的表示方法的数组</td>
</tr>
<tr>
<td>5</td>
<td><strong>复数</strong></td>
</tr>
<tr>
<td><code>a.imag</code></td>
<td>虚部</td>
</tr>
<tr>
<td><code>a.real</code></td>
<td>实部</td>
</tr>
<tr>
<td><code>a.conjugate()</code></td>
<td>复共轭</td>
</tr>
<tr>
<td><code>a.conj()</code></td>
<td>复共轭（缩写）</td>
</tr>
<tr>
<td>6</td>
<td><strong>保存</strong></td>
</tr>
<tr>
<td><code>a.dump(file)</code></td>
<td>将二进制数据存在file中</td>
</tr>
<tr>
<td><code>a.dump()</code></td>
<td>将二进制数据表示成字符串</td>
</tr>
<tr>
<td><code>a.tofile(fid, sep="",format="%s")</code></td>
<td>格式化ASCⅡ码写入文件</td>
</tr>
<tr>
<td>7</td>
<td><strong>查找排序</strong></td>
</tr>
<tr>
<td><code>a.nonzero()</code></td>
<td>返回所有非零元素的索引</td>
</tr>
<tr>
<td><code>a.sort(axis=-1)</code></td>
<td>沿某个轴排序</td>
</tr>
<tr>
<td><code>a.argsort(axis=-1)</code></td>
<td>沿某个轴，返回按排序的索引</td>
</tr>
<tr>
<td><code>a.searchsorted(b)</code></td>
<td>返回将b中元素插入a后能保持有序的索引值</td>
</tr>
<tr>
<td>8</td>
<td><strong>元素数学操作</strong></td>
</tr>
<tr>
<td><code>a.clip(low, high)</code></td>
<td>将数值限制在一定范围内</td>
</tr>
<tr>
<td><code>a.round(decimals=0)</code></td>
<td>近似到指定精度</td>
</tr>
<tr>
<td><code>a.cumsum(axis=None)</code></td>
<td>累加和</td>
</tr>
<tr>
<td><code>a.cumprod(axis=None)</code></td>
<td>累乘积</td>
</tr>
<tr>
<td>9</td>
<td><strong>约简操作</strong></td>
</tr>
<tr>
<td><code>a.sum(axis=None)</code></td>
<td>求和</td>
</tr>
<tr>
<td><code>a.prod(axis=None)</code></td>
<td>求积</td>
</tr>
<tr>
<td><code>a.min(axis=None)</code></td>
<td>最小值</td>
</tr>
<tr>
<td><code>a.max(axis=None)</code></td>
<td>最大值</td>
</tr>
<tr>
<td><code>a.argmin(axis=None)</code></td>
<td>最小值索引</td>
</tr>
<tr>
<td><code>a.argmax(axis=None)</code></td>
<td>最大值索引</td>
</tr>
<tr>
<td><code>a.ptp(axis=None)</code></td>
<td>最大值减最小值</td>
</tr>
<tr>
<td><code>a.mean(axis=None)</code></td>
<td>平均值</td>
</tr>
<tr>
<td><code>a.std(axis=None)</code></td>
<td>标准差</td>
</tr>
<tr>
<td><code>a.var(axis=None)</code></td>
<td>方差</td>
</tr>
<tr>
<td><code>a.any(axis=None)</code></td>
<td>只要有一个不为0，返回真，逻辑或</td>
</tr>
<tr>
<td><code>a.all(axis=None)</code></td>
<td>所有都不为0，返回真，逻辑与</td>
</tr>
</tbody>
</table>

In [1]:
from numpy import *

## 基本属性

In [2]:
a = array([[0,1,2,3],
          [4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
#元素属性
a.dtype

dtype('int32')

In [5]:
#形状
a.shape

(2, 4)

In [7]:
#元素数目
a.size

8

In [8]:
#元素占字节大小
a.itemsize

4

In [10]:
#所有元素所占字节
a.nbytes

32

In [11]:
#数据微度
a.ndim

2

## 形状相关

In [13]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]


所有元素的迭代器：

In [14]:
for elt in a.flat:
    print(elt)

0
1
2
3
4
5
6
7


所有元素组成的一维数组，按照行排列：

In [15]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

重新改变形状：

In [17]:
a.resize((4,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [19]:
a.reshape(2,4)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [23]:
#交换这两个轴的顺序：
a.swapaxes(0,1)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [24]:
#转置
a.transpose()

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [25]:
a.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [26]:
a2 = array([1,2,3])
a2.shape

(3,)

In [27]:
a2.resize((1,3,1))
a2

array([[[1],
        [2],
        [3]]])

In [28]:
#去除长度为1的微度
a2.squeeze()

array([1, 2, 3])

## 填充复制

In [29]:
#复制：
b = a.copy()
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

复制不影响原来的数组：

In [30]:
b[0][0] = -1
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [31]:
#填充
b.fill(4)
b

array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4]])

## 转化

In [32]:
#转化为列表
a.tolist()

[[0, 1], [2, 3], [4, 5], [6, 7]]

In [33]:
#转化为字符串
a.tostring()

b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00'

In [34]:
#改变数组元素类型：
a.astype(float)

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.]])

In [43]:
b = a.copy()
b.byteswap(False)

array([[        0,  16777216],
       [ 33554432,  50331648],
       [ 67108864,  83886080],
       [100663296, 117440512]])

In [37]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [38]:
#将它看成16位整数：
a.view(dtype=int16)

array([[0, 0, 1, 0],
       [2, 0, 3, 0],
       [4, 0, 5, 0],
       [6, 0, 7, 0]], dtype=int16)

## 复数

In [45]:
# 实部
b = array([1+2j, 3+4j, 5+6j])
b.real

array([ 1.,  3.,  5.])

In [46]:
#虚部
b.imag

array([ 2.,  4.,  6.])

In [47]:
#共轭
b.conj()

array([ 1.-2.j,  3.-4.j,  5.-6.j])

In [48]:
b.conjugate()

array([ 1.-2.j,  3.-4.j,  5.-6.j])

## 保存

In [49]:
#保存成文本：
a.dump('file.txt')

In [50]:
#字符串：
a.dumps()

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x02\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i4q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X \x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [53]:
#写入文件
a.tofile('foo.csv', sep=',', format='%s')

## 查找排序

In [54]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [55]:
# 非零元素的索引：
a.nonzero()

(array([0, 1, 1, 2, 2, 3, 3], dtype=int64),
 array([1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [56]:
# 排序
b = array([3,2,7,4,1])
b.sort()
b

array([1, 2, 3, 4, 7])

In [57]:
#排序的索引位置：
b = array([2,3,1])
b.argsort(axis=-1)

array([2, 0, 1], dtype=int64)

In [58]:
#将b插入a中的索引，使得a保持有序：
a = array([1,3,4,6])
b = array([0,2,5])
a.searchsorted(b)

array([0, 1, 3], dtype=int64)

## 元素数学操作

限制在一定范围：

In [59]:
a = array([[4,1,3],[2,1,5]])
a.clip(0,2)

array([[2, 1, 2],
       [2, 1, 2]])

In [60]:
#近似：
a = array([1.344, 2.449, 2.558])
a.round(decimals=2)

array([ 1.34,  2.45,  2.56])

In [61]:
#累加和
a = array([[4,1,3],[2,1,5]])
a.cumsum()

array([ 4,  5,  8, 10, 11, 16], dtype=int32)

In [62]:
#累乘积：
a.cumprod(axis=None)

array([  4,   4,  12,  24,  24, 120], dtype=int32)

## 约简操作

In [63]:
# 求和
a = array([[4,1,3],[2,1,5]])
a.sum(axis=None)

16

In [64]:
#求积
a.prod()

120

In [65]:
#最小值
a.min()

1

In [66]:
#最大值
a.max()

5

In [67]:
#最小值索引
a.argmin()

1

In [68]:
#最大值索引
a.argmax()

5

In [70]:
#最大值间隔
a.ptp()

4

In [71]:
#均值
a.mean()

2.6666666666666665

In [72]:
#标准差
a.std()

1.49071198499986

In [73]:
#方差：
a.var()

2.2222222222222228

In [74]:
#是否有非零元素：
a.any()

True

In [75]:
# 是否全部非零：
a.all()

True